Database:
  MySQL:
    enabled: false
    host: localhost
    port: 3306
    database: playerData
    username: root
    password:
  SQLite:
    Filename:
default_gender: "fe"
command_withdraws:
  marry_proposing_player: 10.0
  marry_proposed_player: 10.0
  marry_priest: 10.0
  marry_priest_player: 10.0
  marry_divorce_leaving_player: 10.0
  marry_divorce_left_player: 10.0
  adopt_parent: 10.0
  adopt_child: 10.0
  adopt_kickout_parent: 10.0
  adopt_kickout_child: 10.0
  adopt_moveout_parent: 10.0
  adopt_moveout_child: 10.0
  sibling_proposing_player: 10.0
  sibling_proposed_player: 10.0
  sibling_unsibling_leaving_player: 10.0
  sibling_unsibling_left_player: 10.0
default_background: "moss_block"
backgrounds:
  - "moss_block"
  - "oak_planks"
  - "red_wool"
  - "pink_wool"
  - "diamond_block"
  - "gold_block"
allow_single_adopt: true
language: "DE"

family_list:
  - partner
  - sibling
  - firstChild
  - secondChild
  - firstParent
  - secondParent
  - firstGrandchild
  - secondGrandchild
  - thirdGrandchild
  - fourthGrandchild
  - firstGrandparent
  - secondGrandparent
  - thirdGrandparent
  - fourthGrandparent
  - firstParentInLaw
  - secondParentInLaw
  - firstChildInLaw
  - secondChildInLaw
  - firstAuntOrUncle
  - secondAuntOrUncle
  - thirdAuntOrUncle
  - fourthAuntOrUncle
  - firstSiblingInLaw
  - secondSiblingInLaw
  - firstCousin
  - secondCousin
  - thirdCousin
  - fourthCousin
  - firstNieceOrNephew
  - secondNieceOrNephew
  - firstGreatGrandparent
  - secondGreatGrandparent
  - thirdGreatGrandparent
  - fourthGreatGrandparent
  - fifthGreatGrandparent
  - sixthGreatGrandparent
  - seventhGreatGrandparent
  - eighthGreatGrandparent
  - firstGreatAuntOrUncle
  - secondGreatAuntOrUncle
  - thirdGreatAuntOrUncle
  - fourthGreatAuntOrUncle
  - firstGrandchildInLaw
  - secondGrandchildInLaw
  - thirdGrandchildInLaw
  - fourthGrandchildInLaw
  - firstGreatGrandchild
  - secondGreatGrandchild
  - thirdGreatGrandchild
  - fourthGreatGrandchild
  - fifthGreatGrandchild
  - sixthGreatGrandchild
  - seventhGreatGrandchild
  - eighthGreatGrandchild

