name: Family
version: '${project.version}'
main: de.janschuri.lunaticFamily.Main
commands:
  family:
    description: Get information about your family.
  marry:
    description: Get married.
  adopt:
    description: Adopt or get adopted.
  gender:
    description: Change your gender.
  sibling:
    description: Get yourself a sibling without having parents.
permissions:
  lunaticFamily.adopt:
    description: Use /adopt Command.
  lunaticFamily.marry:
    description: Use /marry Command.
  lunaticFamily.marry.priest:
    description: Use /marry priest Command.
  lunaticFamily.family.list:
    description: List own family.
  lunaticFamily.family.list.others:
    description: List others family.
  lunaticFamily.admin.marry:
    description: Set and unset Marriage by command.
  lunaticFamily.admin.reload:
    description: Reload Plugin Config.
  lunaticFamily.admin.adopt:
    description: Set and unset Adoption by command.
api-version: 1.20
softdepend:
  - CrazyAdvancementAPI
