name: Family
version: '${project.version}'
main: de.janschuri.lunaticfamily.Main
commands:
  family:
    description: Get information about your family.
  marry:
    description: Get married.
  adopt:
    description: Adopt or get adopted.
  sibling:
    description: Get yourself a sibling without having parents.
permissions:
  family.adopt:
    description: Adopt and get adopted.
  family.list:
    description: List own family.
  family.list.others:
    description: List others family.
  family.admin.marry:
    description: Marry and get Married.
api-version: 1.20
