name: LunaticFamily
version: '${project.version}'
main: de.janschuri.lunaticFamily.LunaticFamily
commands:
  family:
    description: Get information about your family.
  marry:
    description: Get married.
  adopt:
    description: Adopt or get adopted.
  gender:
    description: Change your gender.
  sibling:
    description: Get yourself a sibling without having parents.
permissions:
  lunaticFamily.adopt:
    description: Use /adopt Command.
  lunaticFamily.marry:
    description: Use /marry Command.
  lunaticFamily.sibling:
    description: Use /marry Command.
  lunaticFamily.family.background:
    description: Use /family background.
  lunaticFamily.marry.priest:
    description: Use /marry priest Command.
  lunaticFamily.family.list:
    description: List own family.
  lunaticFamily.family.list.others:
    description: List others family.
  lunaticFamily.admin.adopt:
    description: Set and unset adoption by command.
  lunaticFamily.admin.marry:
    description: Set and unset marriage by command.
  lunaticFamily.admin.sibling:
      description: Set and unset siblinghood by command.
lunaticFamily.admin.gender:
      description: Set genders of players by command.
api-version: 1.20
softdepend:
  - CrazyAdvancementAPI
  - Vault
  - Minepacks
