name: LunaticFamily
version: 1.0.0
main: de.janschuri.lunaticFamily.PaperLunaticFamily
api-version: '1.20'
author: Janschuri
description: A plugin that allows you to create a family tree.
depend:
  - LunaticLib
softdepend:
  - CrazyAdvancementAPI
  - Vault
commands:
  family:
    description: Get information about your family.
  marry:
    description: Get married.
  adopt:
    description: Adopt a child.
  gender:
    description: Change your gender.
  sibling:
    description: Get yourself a sibling without having parents.
permissions:
  lunaticFamily.adopt:
    description: Use /adopt
  lunaticFamily.marry:
    description: Use /marry
  lunaticFamily.sibling:
    description: Use /marry
  lunaticFamily.gender:
    description: Use /gender
  lunaticFamily.family:
    description: Use /family
  lunaticFamily.family.background:
    description: Use /family background
  lunaticFamily.marry.priest:
    description: Use /marry priest
  lunaticFamily.marry.gift:
    description: Use /marry gift
  lunaticFamily.marry.heart:
    description: Use /marry heart
  lunaticFamily.marry.heart.color.*:
    description: Use /marry heart <color>
  lunaticFamily.marry.heart.hex:
    description: Use /marry heart <hex>
  lunaticFamily.family.list:
    description: Use /family list
  lunaticFamily.family.list.others:
    description: Use /family list <player>
  lunaticFamily.admin.adopt:
    description: Use adopt admin commands
  lunaticFamily.admin.marry:
    description: Use marry admin commands
  lunaticFamily.admin.sibling:
    description: Use sibling admin commands
  lunaticFamily.admin.gender:
    description: Use gender admin commands
  lunaticFamily.admin.reload:
    description: Use reload command
