package de.janschuri.lunaticfamily.common.utils;

public enum WithdrawKey {
    MARRY_PROPOSING_PLAYER,
    MARRY_PROPOSED_PLAYER,
    MARRY_PRIEST,
    MARRY_PRIEST_PLAYER,
    MARRY_DIVORCE_LEAVING_PLAYER,
    MARRY_DIVORCE_LEFT_PLAYER,
    ADOPT_PARENT,
    ADOPT_CHILD,
    ADOPT_KICKOUT_PARENT,
    ADOPT_KICKOUT_CHILD,
    ADOPT_MOVEOUT_PARENT,
    ADOPT_MOVEOUT_CHILD,
    SIBLING_PROPOSING_PLAYER,
    SIBLING_PROPOSED_PLAYER,
    SIBLING_UNSIBLING_LEAVING_PLAYER,
    SIBLING_UNSIBLING_LEFT_PLAYER,
}
